### ISSUE TITLE
Output spec-compliant JSON

### ISSUE THREAD

**Issue by mjswensen** [mjswensen/pcn-audit#4]
Provisions should be made for a user to save the JSON. Options we've considered so far:
- Save to a user account (would require the development of a server-side application)
- Email (would require the development of a server-side application, or finding a public API for sending mail)
- Download as file (would work great for desktop browsers but maybe not for mobile)
- Copy/paste
  - From on-screen textarea (simplest and most straightforward)
  - Via browser's clipboard API (better UX than manual copy/paste)

**Comment by brookefrichards** [comment]
The most common way of copying to the clipboard is with flash, which is not the best solution for a mobile-friendly site. I've added a textarea for the json to go in. For now, they can copy/paste from there.

**Comment by morgan-s-young** [comment]
Great job Brooke!

Sincerely,

Morgan S. Young

Master Information Systems Management
Brigham Young University, Provo
Email: morgan.s.young@marriottschool.byu.edu
Cell: (530) 306-9233
